make bind address configurable
micromdm/scep pull request #182
Opened 2022-01-24 18:11 UTC by 9072997

This adds a command line option/environment variable to control the bind address. Previously it was always left blank, causing the server to listen on all addresses. This is still the default behavior. The primary use-case I see for this is for when a user wants the server to only be accessible from localhost (so bind to 127.0.0.1). Another possible use-case would be when a server has both publicly accessible interfaces and internal interfaces, though I expect this configuration is uncommon.

2022-01-24 19:14 UTC, groob commented
I would prefer a flag like `-http-addr` which defaults to `:port`, meaning `0.0.0.0:8080`, but can be `127.0.0.1:port` if needed. The new `-http-addr` flag would be used over the `-port` flag if specified, so that things remain backwards compatible. 

This is how micromdm/micromdm is configured as well, I'm surprised the SCEP binary didn't already have it. 
https://github.com/micromdm/micromdm/blob/ba387818b045d71a24989f9ab85585c681a2694a/cmd/micromdm/serve.go#L111

2022-01-26 21:07 UTC, jessepeterson requested changes
I second @groob's request here.

2022-01-26 22:37 UTC, 9072997 commented
How's this? There is now a `-http-addr` flag in the format `127.0.0.1:1234` in addition to the old `-port`. If both are set, either via flags or environment variables, the program will refuse to start.

2022-05-07 20:46 UTC, jessepeterson commented
I'm not thrilled by the custom flag shenanigans. But as a migration solution until a later time, I'm good with this for now.

2022-05-07 20:47 UTC, merged