Add DNSName flag to scepclient
micromdm/scep pull request #202
Opened 2022-08-10 15:36 UTC by macmule

Whilst DNSNames have been referenced in the cert template (https://github.com/micromdm/scep/blob/main/depot/signer.go#L81-L97), neither the scepclient did not have the option to add these to the CSR.

This PR resolves that by adding the option via a dnsname flag.

This could be improved upon though by adding multiple, but a little beyond my 1 days worth of Go experience.

2022-08-10 15:43 UTC, jessepeterson requested changes

2022-08-10 15:43 UTC, jessepeterson commented on cmd/scepclient/csr.go
> +	cn, org, country, ou, locality, province, dnsnames, challenge string
```suggestion
	cn, org, country, ou, locality, province, dnsName, challenge string
```

[mixedCaps](https://go.dev/doc/effective_go#mixed-caps) :) also made this singular as its a single string.

2022-08-10 15:55 UTC, macmule commented
Sorry, made another commit which caught the changes after the mixedCaps miss

2022-08-13 16:00 UTC, macmule commented
ran via `gofmt -s` each file flagged with `gofmt -s -l` a few times.. and `gofmt -w`.. now `gofmt -s -l`  has no output.. so fingers crossed this has worked.

2022-08-13 16:32 UTC, jessepeterson approved these changes
lgtm; Thanks!

2022-08-13 16:33 UTC, merged